name=input("enter your name : ")
age=input("enter your age : ")
DOB=input("enter your DOB : ")
location=input("enter your location : ")
college_name=input("enter your college name : " )
print("Hello,my name is",name, " .I am" ,age ,"years old and i was born in" ,DOB, ". Currently,I am located in ",location,"and i have completed my degree at",college_name,".")
